#!/usr/bin/env bash

set -e

bundle exec rake

cd example/a
bundle exec tldr | grep "😁😁"
cd ../..

cd example/b
bundle exec ruby -Itest test/some_test.rb | grep "😁"
bundle exec rake tldr | grep "😁"
cd ../..
